import { useState } from "react";
import { Link } from "react-router-dom";
import { orders, deliveryPartners } from "../../data";
import { OrderCard } from "./DeliveryDashboard";
const steps=["Reached at Restaurant","Picked Up the Parcel","On the Way to Customer","Reached at Destination","Order Delivered"];
export default function ActiveDelivery(){const [order,setOrder]=useState(orders.find(o=>o.deliveryPartnerId==="DEL-001"&&o.orderStatus!=="Delivered")||orders[2]); const [step,setStep]=useState(0); const [qr,setQr]=useState(false); const [success,setSuccess]=useState(false); const [onlineMark,setOnlineMark]=useState(false); const [trip,setTrip]=useState(0); const complete=()=>{setStep(4);setSuccess(true);setOrder({...order,orderStatus:"Delivered"});localStorage.setItem("yubiDeliveryPartners",JSON.stringify(deliveryPartners.map(p=>p.id==="DEL-001"?{...p,status:"Available",currentOrderId:null}:p)));setOnlineMark(true)}; const startNavigation=()=>{const destination=encodeURIComponent(order.customerAddress);window.location.href=`https://www.google.com/maps/dir/?api=1&destination=${destination}&travelmode=driving`;let progress=0;const id=setInterval(()=>{progress+=25;setTrip(progress);if(progress>=100){clearInterval(id);setStep(3);}},1000)}; const click=()=>{if(step===2){startNavigation();return;} if(step===3){ if(order.paymentMethod==="COD") setQr(true); else setStep(4);} else setStep(step+1)}; return <div style={{color:"#1A1A1A"}}><h1 style={{color:"#1A2E1A"}}>Active Delivery</h1><div style={{background:"linear-gradient(145deg,#FFFFFF,#F5FFF5)",border:"1px solid #D6E8D6",borderRadius:18,padding:12,boxShadow:"0 14px 30px rgba(26,46,26,.08)"}}><OrderCard order={order}/></div><div style={{background:"#FFFFFF",borderRadius:16,padding:24,marginTop:16,border:"1px solid #D6E8D6",boxShadow:"0 14px 30px rgba(26,46,26,.07)"}}>{steps.map((s,i)=><div key={s} style={{display:"flex",gap:14,alignItems:"center",marginBottom:18,flexWrap:"wrap"}}><div style={{width:30,height:30,borderRadius:"50%",background:i<step||success?"#4CAF50":i===step?"#A5D6A7":"#EEEEEE",color:i<=step||success?"#FFFFFF":"#888888",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:800}}>{i<step||success?"✓":i+1}</div><div style={{flex:1,color:i<=step?"#1A2E1A":"#888888",fontWeight:i===step?800:600,minWidth:160}}>{s}</div>{i===step&&!success&&i<4&&<button onClick={click} style={btn}>{s}</button>}{i===4&&step===4&&!success&&<button onClick={complete} style={btn}>Mark as Delivered</button>}</div>)}
  {step===2&&trip>0&&trip<100&&<div style={{marginTop:10}}><div style={{fontWeight:700,color:"#1A2E1A",marginBottom:6}}>Moving towards customer: {trip}%</div><div style={{height:10,borderRadius:999,background:"#E5E7EB",overflow:"hidden"}}><div style={{height:"100%",width:`${trip}%`,background:"#4CAF50",transition:"width .4s ease"}}/></div></div>}
</div>{success&&<div style={{marginTop:16,padding:18,background:"#DCFCE7",borderRadius:8,color:"#1A2E1A",fontWeight:800}}>Order Delivered Successfully! ✅ Partner status: {onlineMark?"Available":""}<div style={{marginTop:10}}>Order ID: {order.id} | Customer: {order.customerName} | Amount: ₹{order.total} | Time taken: 34 min</div><Link to="/delivery-partner/dashboard" style={{display:"inline-block",marginTop:12,background:"#4CAF50",color:"#FFFFFF",padding:"10px 14px",borderRadius:8,textDecoration:"none"}}>Back to Dashboard</Link></div>}{qr&&<div style={backdrop}><div style={modal}><h2 style={{color:"#1A2E1A"}}>Collect Payment from Customer</h2><h3 style={{color:"#4CAF50"}}>Amount to collect: ₹{order.total}</h3><img src={`https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=upi://pay?pa=yubifoods@upi%26am=${order.total}%26cu=INR`} alt="UPI QR" style={{width:250,height:250}}/><p style={{color:"#1A1A1A"}}>Show this QR to customer for UPI payment</p><button onClick={()=>{setQr(false);complete();}} style={{...btn,width:"100%"}}>Payment Received ✓ Mark as Delivered</button></div></div>}</div>}
const btn={background:"#4CAF50",color:"#FFFFFF",border:"none",borderRadius:10,padding:"10px 14px",fontWeight:800,cursor:"pointer"}; const backdrop={position:"fixed",inset:0,background:"rgba(0,0,0,.45)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:2000}; const modal={background:"#FFFFFF",borderRadius:10,padding:24,maxWidth:380,width:"90%",textAlign:"center"};
